<h1>Multi_Linear_Regression</h1>

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [6]:
df= pd.read_csv("homepricesM.csv")

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
df.isnull().sum()  #here is the null values so to handle it.

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [9]:
df.bedrooms.median()

4.0

In [10]:
# drop 5th row
df= df.drop(df.index[5])

In [11]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

<h2> Data preprocessing</h2>

In [12]:

import math 
median_bedrooms= math.floor(df.bedrooms.median())

In [13]:
median_bedrooms

3

In [14]:
# fill na value

In [15]:
df.bedrooms.fillna(median_bedrooms) #na value is filled out with 3.

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [16]:
# so update my dataFrame

In [17]:
df.bedrooms= median_bedrooms= df.bedrooms.fillna(median_bedrooms)

In [18]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [19]:
# trained model
reg= linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [20]:
# got cofficient

In [21]:
reg.coef_

# internally working-> y= m*x+b
# m1+m2+m3->> cofficient

#b-> intercept_
#x-> feature variable

array([   137.25, -26025.  ,  -6825.  ])

In [22]:
# intercept
reg.intercept_

383724.9999999998

In [23]:
# finally predict value of price?

In [24]:
reg.predict([[3000, 3.0, 20]])

C:\Users\lenovo\AnacondaFolder\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([580900.])

How this price is calculated?

In [25]:
# cofficient1 * sqrFoot + anotherCofff2 * bedrooms + oneAnothCoff3 * ages + intercept_

137.25 * 3000 +  -26025*3 +  -6825*40+ 383724.99999999983

444399.9999999998

In [26]:
# similar to predict the price of home

In [27]:
reg.predict([[2500, 4, 5]])

C:\Users\lenovo\AnacondaFolder\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [28]:
# trained model?

In [29]:
import pickle

In [31]:
with open ('model_pickle', 'wb') as f:     #write file
    pickle.dump(reg, f)

In [32]:
with open('model_pickle', 'rb') as f:          #read file
    mp= pickle.load(f)

In [48]:
# check your model trained
mp.predict([[2500, 4, 5]])

C:\Users\lenovo\AnacondaFolder\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [ ]:
# two are API        ?
# pickle
# sklearn-> joblib

In [52]:
# more efficient to take it
import joblib

In [57]:
from sklearn.externals import joblib   #joblib-> can take the file name directly

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\lenovo\AnacondaFolder\anaconda3\Lib\site-packages\sklearn\externals\__init__.py)

In [54]:
# import first joblib
# !pip install joblib

In [56]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [58]:
mj= joblib.load('model_joblib')

In [ ]:
# actual prediction

In [59]:
mj.predict([[3000, 2, 5]])

C:\Users\lenovo\AnacondaFolder\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([709300.])

In [60]:
mj.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [61]:
mj.intercept_

383724.9999999998